### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by jaime-olivares** [bbc/fluent-xslt#1]
You should mention that you have a dependency with a native binary: /usr/bin/xsltproc

**Comment by jmbeach** [comment]
@jaime-olivares yeah. Also not windows friendly.

**Comment by adriaannortje** [comment]
To make windows friendly:
1. Install chocolatey https://chocolatey.org/docs/installation
2. >choco xsltproc
3. make sure xsltproc is in path: >where xsltproc
4. take hard-coded path out of reference to xsltproc in index.js at line 8
  var cmd = spawn('/usr/bin/xsltproc', [stylesheetPath, '-'])
  remove /usr/bin/ or change to windows style reference to where xsltproc installed
